//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDNianBot.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JDNianBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{&quot;questionId&quot;:&quot;1901441674&quot;,&quot;questionIndex&quot;:&quot;1&quot;,&quot;questionStem&quot;:&quot;永乐宫位于山西哪个城市？&quot;,&quot;options&quot;:&quot;[{\&quot;optionId\&quot;:\&quot;Ks0Sx0BXjjgbNFBxCgQpCIXLkJ_WAKDLFdSw-A\&quot;,\&quot;optionDesc\&quot;:\&quot;运城市\&quot;},{\&quot;optionId\&quot;:\&quot;Ks0Sx0BXjjgbNFBxCgQpChYv-iBINKeZnfm57Q\&quot;,\&quot;optionDesc\&quot;:\&quot;大同市\&quot;},{\&quot;optionId\&quot;:\&quot;Ks0Sx0BXjjgbNFBxCgQpC0PrO6mXfvErnsQZkw\&quot;,\&quot;optionDesc\&quot;:\&quot;太原市\&quot;}]&quot;,&quot;questionToken&quot;:&quot;Ks0Sx0BXjjgbNFAjGUwyXaBp4FnRWXz9HV3vlG-r0AbqW0JofD5caaNEQRrh9w29L7dXXyJ1x5jxRzvj8WP7hQBiWb6eYw&quot;,&quot;correct&quot;:&quot;{\&quot;optionId\&quot;:\&quot;Ks0Sx0BXjjgbNFBxCgQpCIXLkJ_WAKDLFdSw- [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SXSYTK {
            get {
                return ResourceManager.GetString("SXSYTK", resourceCulture);
            }
        }
    }
}
